spring:
  datasource:
    url: 'jdbc:h2:mem:library'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: '/h2-console'


jwt:
  secret: LWQgdGhpc2lzbXlsaWJyYXJ5cHJvamVjdHNlY3JldGtleTEyMzQ1Ngo=