drop table if exists book CASCADE;
drop table if exists user CASCADE;
drop table if exists user_loan_history CASCADE;
drop table if exists company CASCADE;
drop table if exists employee CASCADE;

create table book (
    id          bigint generated by default as identity,
    name        varchar(255),
    type        varchar(255),
    publisher   varchar(255),
    stock       int,
    version     bigint,
    created_at  datetime null,
    updated_at  datetime null,
    primary key (id)
);


create table user (
    id          bigint generated by default as identity,
    email       varchar(80),
    name        varchar(255),
    password    varchar(255),
    created_at  datetime null,
    updated_at  datetime null,
    primary key (id)
);


create table user_loan_history (
    id          bigint generated by default as identity,
    book_id     bigint,
    status      varchar(255),
    user_id     bigint,
    created_at  datetime null,
    updated_at  datetime null,
    primary key (id)
);

create table company (
    id                 bigint generated by default as identity,
    domain_name        varchar(255),
    number_of_employee bigint,
    status             varchar(255),
    created_at         datetime null,
    updated_at         datetime null,
    primary key (id)
);

create table employee (
    id                  bigint generated by default as identity,
    user_id             bigint,
    company_id          bigint,
    status              varchar(255),
    created_at          datetime null,
    updated_at          datetime null,
    primary key (id)
);