drop table if exists book CASCADE;
drop table if exists users CASCADE;
drop table if exists user_loan_history CASCADE;
drop table if exists company CASCADE;
drop table if exists employee CASCADE;

create table book (
    id          bigint generated by default as identity,
    name        varchar(255),
    type        varchar(255),
    publisher   varchar(255),
    stock       int,
    version     bigint,
    created_at  datetime null,
    updated_at  datetime null,
    primary key (id)
);


create table users (
    id          bigint generated by default as identity,
    mail_id     varchar(80),
    domain      varchar(80),
    name        varchar(255),
    password    varchar(255),
    company_id  bigint,
    created_at  datetime null,
    updated_at  datetime null,
    primary key (id)
);


create table user_loan_history (
    id          bigint generated by default as identity,
    book_id     bigint,
    status      varchar(255),
    user_id     bigint,
    created_at  datetime null,
    updated_at  datetime null,
    primary key (id)
);

create table company (
    id                   bigint generated by default as identity,
    domain               varchar(255),
    number_of_employee   bigint,
    status               varchar(255),
    created_at           datetime null,
    updated_at           datetime null,
    primary key (id)
);

create table employee (
    id                  bigint generated by default as identity,
    user_id             bigint,
    company_id          bigint,
    status              varchar(255),
    created_at          datetime null,
    updated_at          datetime null,
    primary key (id)
);

INSERT INTO company (id, domain, number_of_employee, status) VALUES (1, 'ogqcorp.com', 0, 'OPEN');